AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Gateway backed with lambda which in turn interacts wiht Elastic Cache Memcached . 
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    DependsOn: CacheClustrer
    Properties:
      VpcConfig:
        SecurityGroupIds: 
            - sg-1d366565
        SubnetIds: 
            - subnet-b65bcac0
            - subnet-916fb0c9
            - subnet-f10c7595
      Handler: index.get
      Runtime: nodejs4.3
      CodeUri: s3://gw-sam-apiwithlambda-cach2/index.zip
      Policies: AdministratorAccess
      Environment:
        Variables:
          CACHE_ENDPOINT: 
            !Join [":",[!GetAtt CacheCluster.ConfigurationEndpoint.Address,!GetAtt CacheCluster.ConfigurationEndpoint.Port]]         
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get

  CacheCluster:
        Type: 'AWS::ElastiCache::CacheCluster'
        
        Properties:
            CacheNodeType: cache.t2.micro
            VpcSecurityGroupIds: 
                - sg-1d366565
            Engine: memcached
            NumCacheNodes: '1'
